name: Docker

on:
  release:
    types: [released]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Build Docker image
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        uses: X-Stock/shared-workflow/.github/workflows/docker-publish.yml@main
        with:
          package-name: plutus